export type AppTheme = Partial<{
  themeClass: string;
  spacing: Partial<{ baseUnit: number; controlHeight: number }>;
  borderRadius: number;
  fontSize: number;
  colors: Partial<{
    accent: string;
    borderColor: string;
    canvasBackground: string;
    danger: string;
    dangerLight: string;
    error: string;
    evenBackground: string;
    focusColor: string;
    mutedColor: string;
    neutral0: string;
    neutral10: string;
    neutral20: string;
    neutral30: string;
    neutral40: string;
    neutral50: string;
    neutral5: string;
    neutral60: string;
    neutral70: string;
    neutral80: string;
    neutral90: string;
    ok: string;
    primary25: string;
    primary50: string;
    primary75: string;
    primary: string;
    primaryBackground: string;
    primaryColor: string;
    secondaryBackground: string;
    secondaryColor: string;
    selectedValue: string;
    sucess: string;
    warning: string;
  }>;
}>;
